name: TheBookOfBabylonians
version: 0.0.1
description: A block logging plugin by TilionDC
author: TilionDC
website: dev.bukkit.org
 
main: me.tiliondc.Plugin
database: false

commands:
  book:
    description: Gives you the book of babylonians
    usage: /book to get the book